#Uppgift: Lägg till exception för att hantera fel
#som kan uppstå vid körning av koden.

numerator = 10
denominator = 0

result = numerator / denominator
print("Result:", result)
